# Generated by Django 5.1.2 on 2024-10-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotempo',
            name='horas_trabalhadas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='nome_usuario',
            field=models.CharField(max_length=100),
        ),
    ]
